all:
  doctrine_menu:
    # If enabled, label will become an i18n field
    use_i18n: false

    # The routing prefix to use for the menu admin module
    module_prefix:  /admin/menu

    cache:
      enabled:  true
      class:    sfFileCache
      options:
        cache_dir:  <?php echo sfConfig::get('sf_app_cache_dir') ?>/io_doctrine_menu