ioDoctrineMenuItem:
  actAs:
    Timestampable:
    NestedSet:
      hasManyRoots:   true
      rootColumnName: root_id
# Add i18n conditionally
<?php if (sfConfig::get('app_doctrine_menu_use_i18n', false)): ?>
    I18n:
      fields:         [label]
<?php endif; ?>
  columns:
    name:
      type:           string(255)
      notnull:        true
    root_id:          integer
    class:            string(255)
    label:            string(255)
    route:            string(255)
    attributes:       string(255)
    requires_auth:    boolean
    requires_no_auth: boolean
  relations:
    RootMenuItem:
      local:        root_id
      class:        ioDoctrineMenuItem
      onDelete:     CASCADE
      autoComplete: false
    Permissions:
      class:        sfGuardPermission
      local:        menu_item_id
      foreign:      permission_id
      refClass:     ioDoctrineMenuPermission
      foreignAlias: MenuItems
      onDelete:     CASCADE

# many-to-many so that ioDoctrineMenu can have many doctrine permissions, used for menu credentials
ioDoctrineMenuPermission:
  columns:
    menu_item_id:
      primary:  true
      type:     integer
    permission_id:
      primary:  true
      type:     integer
  options:
    symfony:
      form:     false
      filter:   false
  relations:
    Menu:
      class:    ioDoctrineMenuItem
      local:    menu_item_id
      onDelete: CASCADE
    Permission:
      class:    sfGuardPermission
      local:    permission_id
      onDelete: CASCADE